name: test-connection-to-gcp
on:
  push
jobs:
  connect-to-gcp:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: 'actions/checkout@v3'
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'

    - uses: actions/setup-python@v4
      with:
        python-version: '3.10' 

    - name: work-work
      run: python test.py